<?php

namespace App\Http\Controllers\Api;

use App\Models\SystemTranslation;
use App\Support\Api\ApiResponse;
use App\Services\Translation\TranslationCacheService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * Translation management controller.
 *
 * WHY THIS CONTROLLER EXISTS:
 * Runtime translation preload endpoint (`/v1/translations`) is read-focused
 * and optimized for SPA hydration.
 *
 * Admin translation management needs a separate endpoint because it requires:
 * - pagination
 * - filters
 * - locale matrix structure
 * - create/update/delete operations
 * - cache invalidation
 * - missing translation visibility
 */
class TranslationManagementController extends BaseController
{
    public function __construct(
        protected TranslationCacheService $translationCache
    ) {
    }

    /**
     * Return translation keys grouped as locale matrix rows.
     *
     * WHY:
     * Admin UI should edit translations by logical key, not by raw DB rows.
     *
     * Instead of showing:
     * - roles.admin EN
     * - roles.admin UK
     * - roles.admin DE
     *
     * we return one row:
     * - roles.admin
     *   - en
     *   - uk
     *   - de
     */
    public function index(Request $request): JsonResponse
    {
        $perPage = min(max((int) $request->query('per_page', 10), 5), 100);
        $search = trim((string) $request->query('search', ''));
        $locale = trim((string) $request->query('locale', ''));
        $group = trim((string) $request->query('group', ''));
        $source = trim((string) $request->query('source', ''));
        $translatedOnly = $request->boolean('translated_only');
        $autogeneratedOnly = $request->boolean('autogenerated_only');
        $active = $request->query('active');

        /*
        |--------------------------------------------------------------------------
        | Locale Matrix Base Query
        |--------------------------------------------------------------------------
        |
        | We group translations by group/key/source so the frontend can show
        | side-by-side locale columns instead of one row per locale.
        */

        $query = SystemTranslation::query()
            ->select([
                DB::raw('MIN(id) as id'),
                'group',
                'key',
                'source',
                DB::raw('MAX(updated_at) as updated_at'),
                DB::raw('MAX(CASE WHEN is_auto_generated = 1 THEN 1 ELSE 0 END) as is_auto_generated'),
                DB::raw('MIN(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) as is_active'),
                DB::raw('MIN(CASE WHEN is_translated = 1 THEN 1 ELSE 0 END) as is_translated'),
            ])
            ->groupBy('group', 'key', 'source')
            ->when($group !== '', fn ($builder) => $builder->where('group', $group))
            ->when($source !== '', fn ($builder) => $builder->where('source', $source))
            ->when($locale !== '', fn ($builder) => $builder->where('locale', $locale))
            ->when($translatedOnly, fn ($builder) => $builder->where('is_translated', true))
            ->when($autogeneratedOnly, fn ($builder) => $builder->where('is_auto_generated', true))
            ->when($active !== null && $active !== '', fn ($builder) => $builder->where('is_active', filter_var($active, FILTER_VALIDATE_BOOLEAN)))
            ->when($search !== '', function ($builder) use ($search): void {
                $builder->where(function ($nested) use ($search): void {
                    $nested->where('group', 'like', "%{$search}%")
                        ->orWhere('key', 'like', "%{$search}%")
                        ->orWhere('value', 'like', "%{$search}%");
                });
            })
            ->orderBy('group')
            ->orderBy('key');

        $paginator = $query->paginate($perPage);
        $rows = collect($paginator->items());

        /*
        |--------------------------------------------------------------------------
        | Load Locale Values For Current Page Only
        |--------------------------------------------------------------------------
        |
        | Pagination happens on logical translation keys. After that we load all
        | locale rows only for keys visible on the current page.
        |
        | This avoids loading the full translations table for every request.
        */

        $pairs = $rows->map(fn ($row) => [
            'group' => $row->group,
            'key' => $row->key,
            'source' => $row->source,
        ])->values();

        $localesByPair = [];

        if ($pairs->isNotEmpty()) {
            $translations = SystemTranslation::query()
                ->where(function ($builder) use ($pairs): void {
                    foreach ($pairs as $pair) {
                        $builder->orWhere(function ($nested) use ($pair): void {
                            $nested->where('group', $pair['group'])
                                ->where('key', $pair['key'])
                                ->where('source', $pair['source']);
                        });
                    }
                })
                ->orderBy('locale')
                ->get([
                    'id',
                    'locale',
                    'group',
                    'key',
                    'source',
                    'value',
                    'is_translated',
                    'is_auto_generated',
                    'is_active',
                    'updated_at',
                    'description',
                ]);

            foreach ($translations as $translation) {
                $index = $translation->group . '::' . $translation->key . '::' . $translation->source;
                $localesByPair[$index] ??= [];
                $localesByPair[$index][$translation->locale] = [
                    'id' => $translation->id,
                    'locale' => $translation->locale,
                    'value' => $translation->value,
                    'is_translated' => (bool) $translation->is_translated,
                    'is_auto_generated' => (bool) $translation->is_auto_generated,
                    'is_active' => (bool) $translation->is_active,
                    'description' => $translation->description,
                    'updated_at' => optional($translation->updated_at)?->toISOString(),
                ];
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Build Frontend-Friendly Matrix Items
        |--------------------------------------------------------------------------
        */

        $items = $rows->map(function ($row) use ($localesByPair) {
            $index = $row->group . '::' . $row->key . '::' . $row->source;
            return [
                'id' => (int) $row->id,
                'group' => $row->group,
                'key' => $row->key,
                'source' => $row->source,
                'is_translated' => (bool) $row->is_translated,
                'is_auto_generated' => (bool) $row->is_auto_generated,
                'is_active' => (bool) $row->is_active,
                'updated_at' => $row->updated_at,
                'locales' => $localesByPair[$index] ?? [],
            ];
        })->values();

        return ApiResponse::success(
            $items,
            dt('notifications.success'),
            200,
            [
                'current_page' => $paginator->currentPage(),
                'last_page' => $paginator->lastPage(),
                'per_page' => $paginator->perPage(),
                'total' => $paginator->total(),

                /*
                |--------------------------------------------------------------------------
                | Filter Dictionaries
                |--------------------------------------------------------------------------
                |
                | These values allow frontend filters to stay backend-driven.
                */

                'groups' => SystemTranslation::query()
                    ->select('group')
                    ->distinct()
                    ->orderBy('group')
                    ->pluck('group')
                    ->values()
                    ->all(),

                'sources' => SystemTranslation::query()
                    ->select('source')
                    ->distinct()
                    ->orderBy('source')
                    ->pluck('source')
                    ->values()
                    ->all(),

                'locales' => SystemTranslation::query()
                    ->select('locale')
                    ->distinct()
                    ->orderBy('locale')
                    ->pluck('locale')
                    ->values()
                    ->all(),
            ]
        );
    }

    /**
     * Create a new translation key with values for one or more locales.
     */
    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'group' => ['required', 'string', 'max:100'],
            'key' => ['required', 'string', 'max:191'],
            'source' => ['nullable', 'string', 'max:50'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
            'is_auto_generated' => ['nullable', 'boolean'],
            'values' => ['required', 'array', 'min:1'],
            'values.*' => ['nullable', 'string'],
        ]);

        $group = $validated['group'];
        $key = $validated['key'];
        $source = $validated['source'] ?? 'database';
        $isActive = (bool) ($validated['is_active'] ?? true);
        $isAutoGenerated = (bool) ($validated['is_auto_generated'] ?? false);
        $description = $validated['description'] ?? null;
        $values = $validated['values'];

        /*
        |--------------------------------------------------------------------------
        | Transactional Multi-Locale Create
        |--------------------------------------------------------------------------
        |
        | A translation key should be created consistently across locales.
        | If one locale insert fails, the whole operation rolls back.
        */

        DB::transaction(function () use ($group, $key, $source, $isActive, $isAutoGenerated, $description, $values): void {
            foreach ($values as $locale => $value) {
                if (!is_string($locale) || trim($locale) === '' || $value === null || trim((string) $value) === '') {
                    continue;
                }

                SystemTranslation::query()->updateOrCreate(
                    [
                        'locale' => $locale,
                        'group' => $group,
                        'key' => $key,
                    ],
                    [
                        'value' => trim((string) $value),
                        'source' => $source,
                        'description' => $description,
                        'is_active' => $isActive,
                        'is_auto_generated' => $isAutoGenerated,
                        'is_translated' => ! $isAutoGenerated,
                        'is_frontend' => true,
                        'is_backend' => true,
                        'updated_by' => auth()->id(),
                        'created_by' => auth()->id(),
                    ]
                );
            }
        });

        $this->invalidateTranslationCaches($group, $key, array_keys($values));

        return $this->successResponse(['saved' => true], dt('notifications.created'), 201);
    }

    /**
     * Update all locale values for an existing logical translation key.
     */
    public function update(Request $request, int $translation): JsonResponse
    {
        $validated = $request->validate([
            'source' => ['nullable', 'string', 'max:50'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
            'is_auto_generated' => ['nullable', 'boolean'],
            'values' => ['required', 'array', 'min:1'],
            'values.*' => ['nullable', 'string'],
        ]);

        /*
        |--------------------------------------------------------------------------
        | Seed Translation Row
        |--------------------------------------------------------------------------
        |
        | The route receives one row id, but the UI edits the full locale matrix.
        | This row is used only to discover group/key/source.
        */

        $seed = SystemTranslation::query()->findOrFail($translation);

        $source = $validated['source'] ?? $seed->source;
        $description = $validated['description'] ?? $seed->description;
        $isActive = (bool) ($validated['is_active'] ?? $seed->is_active);
        $isAutoGenerated = (bool) ($validated['is_auto_generated'] ?? $seed->is_auto_generated);
        $values = $validated['values'];

        DB::transaction(function () use ($seed, $source, $description, $isActive, $isAutoGenerated, $values): void {
            foreach ($values as $locale => $value) {
                if (!is_string($locale) || trim($locale) === '') {
                    continue;
                }

                $payload = [
                    'source' => $source,
                    'description' => $description,
                    'is_active' => $isActive,
                    'is_auto_generated' => $isAutoGenerated,
                    'is_translated' => $value !== null && trim((string) $value) !== '',
                    'is_frontend' => true,
                    'is_backend' => true,
                    'updated_by' => auth()->id(),
                ];

                if ($value !== null && trim((string) $value) !== '') {
                    $payload['value'] = trim((string) $value);
                    $payload['created_by'] = auth()->id();

                    SystemTranslation::query()->updateOrCreate(
                        [
                            'locale' => $locale,
                            'group' => $seed->group,
                            'key' => $seed->key,
                        ],
                        $payload,
                    );
                }
            }
        });

        $this->invalidateTranslationCaches($seed->group, $seed->key, array_keys($values));

        return $this->successResponse(['saved' => true], dt('notifications.updated'));
    }

    /**
     * Delete the full translation matrix for selected group/key/source.
     */
    public function destroy(int $translation): JsonResponse
    {
        $seed = SystemTranslation::query()->findOrFail($translation);
        $locales = SystemTranslation::query()
            ->where('group', $seed->group)
            ->where('key', $seed->key)
            ->pluck('locale')
            ->unique()
            ->values()
            ->all();

        /*
        |--------------------------------------------------------------------------
        | Matrix Delete
        |--------------------------------------------------------------------------
        |
        | Deleting one visible row in the admin table removes all locale rows
        | belonging to the same group/key/source.
        */

        SystemTranslation::query()
            ->where('group', $seed->group)
            ->where('key', $seed->key)
            ->where('source', $seed->source)
            ->delete();

        $this->invalidateTranslationCaches($seed->group, $seed->key, $locales);

        return $this->successResponse(['deleted' => true], dt('notifications.deleted'));
    }

    /**
     * Invalidate all cache entries that can contain the updated translation.
     */
    protected function invalidateTranslationCaches(string $group, string $key, array $candidateLocales = []): void
    {
        $persistedLocales = SystemTranslation::query()
            ->where('group', $group)
            ->where('key', $key)
            ->pluck('locale')
            ->unique()
            ->values()
            ->all();
        $locales = array_values(array_unique(array_merge($persistedLocales, $candidateLocales)));

        foreach ($locales as $locale) {
            $this->translationCache->forget((string) $locale, $group, $key);
            $this->translationCache->forgetPreload((string) $locale, $group);
            $this->translationCache->forgetPreload((string) $locale);
        }
    }
}

